"""Add stored_filename to Import

Revision ID: 0a868717f44e
Revises: 395ca05739bf
Create Date: 2026-09-28 13:29:59.581382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a868717f44e'
down_revision: Union[str, Sequence[str], None] = '395ca05739bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('stored_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imports', 'stored_filename')
    # ### end Alembic commands ###
