"""make campaign_student_id unique in campaign_submissions

Revision ID: 395ca05739bf
Revises: 9f3400329d5f
Create Date: 2026-09-25 14:45:47.434319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395ca05739bf'
down_revision: Union[str, Sequence[str], None] = '9f3400329d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_submissions_campaign_student_id'), table_name='campaign_submissions')
    op.create_index(op.f('ix_campaign_submissions_campaign_student_id'), 'campaign_submissions', ['campaign_student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_submissions_campaign_student_id'), table_name='campaign_submissions')
    op.create_index(op.f('ix_campaign_submissions_campaign_student_id'), 'campaign_submissions', ['campaign_student_id'], unique=False)
    # ### end Alembic commands ###
