"""add core application schema

Revision ID: 9014a4161e7e
Revises: 60e02b83756f
Create Date: 2026-09-23 16:35:17.881001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9014a4161e7e'
down_revision: Union[str, Sequence[str], None] = '60e02b83756f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_created_by_id'), 'campaigns', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('campaign_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'field_name', name='uq_campaign_field_name')
    )
    op.create_index(op.f('ix_campaign_fields_campaign_id'), 'campaign_fields', ['campaign_id'], unique=False)
    op.create_table('campaign_students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'student_id', name='uq_campaign_student')
    )
    op.create_index(op.f('ix_campaign_students_campaign_id'), 'campaign_students', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_students_status'), 'campaign_students', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_students_student_id'), 'campaign_students', ['student_id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imports_campaign_id'), 'imports', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_imports_status'), 'imports', ['status'], unique=False)
    op.create_index(op.f('ix_imports_uploaded_by_id'), 'imports', ['uploaded_by_id'], unique=False)
    op.create_table('campaign_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_student_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_student_id'], ['campaign_students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_submissions_campaign_student_id'), 'campaign_submissions', ['campaign_student_id'], unique=False)
    op.create_table('imported_field_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_student_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_field_id', sa.Uuid(), nullable=False),
    sa.Column('imported_value', sa.String(length=2048), nullable=True),
    sa.Column('requires_student_input', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_field_id'], ['campaign_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_student_id'], ['campaign_students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_student_id', 'campaign_field_id', name='uq_imported_value_student_field')
    )
    op.create_index(op.f('ix_imported_field_values_campaign_field_id'), 'imported_field_values', ['campaign_field_id'], unique=False)
    op.create_index(op.f('ix_imported_field_values_campaign_student_id'), 'imported_field_values', ['campaign_student_id'], unique=False)
    op.create_index(op.f('ix_imported_field_values_requires_student_input'), 'imported_field_values', ['requires_student_input'], unique=False)
    op.create_table('student_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('imported_field_value_id', sa.Uuid(), nullable=False),
    sa.Column('response_value', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_field_value_id'], ['imported_field_values.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_responses_imported_field_value_id'), 'student_responses', ['imported_field_value_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_responses_imported_field_value_id'), table_name='student_responses')
    op.drop_table('student_responses')
    op.drop_index(op.f('ix_imported_field_values_requires_student_input'), table_name='imported_field_values')
    op.drop_index(op.f('ix_imported_field_values_campaign_student_id'), table_name='imported_field_values')
    op.drop_index(op.f('ix_imported_field_values_campaign_field_id'), table_name='imported_field_values')
    op.drop_table('imported_field_values')
    op.drop_index(op.f('ix_campaign_submissions_campaign_student_id'), table_name='campaign_submissions')
    op.drop_table('campaign_submissions')
    op.drop_index(op.f('ix_imports_uploaded_by_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_status'), table_name='imports')
    op.drop_index(op.f('ix_imports_campaign_id'), table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_campaign_students_student_id'), table_name='campaign_students')
    op.drop_index(op.f('ix_campaign_students_status'), table_name='campaign_students')
    op.drop_index(op.f('ix_campaign_students_campaign_id'), table_name='campaign_students')
    op.drop_table('campaign_students')
    op.drop_index(op.f('ix_campaign_fields_campaign_id'), table_name='campaign_fields')
    op.drop_table('campaign_fields')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_by_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
