"""Add validation_config to CampaignField

Revision ID: 9f3400329d5f
Revises: ecc8021c6466
Create Date: 2026-09-25 14:01:24.983762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f3400329d5f'
down_revision: Union[str, Sequence[str], None] = 'ecc8021c6466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_fields', sa.Column('validation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_fields', 'validation_config')
    # ### end Alembic commands ###
