"""replace password_hash with google_subject_id

Revision ID: ecc8021c6466
Revises: 7860ebd7b6f1
Create Date: 2026-09-24 14:12:30.897739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc8021c6466'
down_revision: Union[str, Sequence[str], None] = '7860ebd7b6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_subject_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_google_subject_id'), 'users', ['google_subject_id'], unique=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_google_subject_id'), table_name='users')
    op.drop_column('users', 'google_subject_id')
    # ### end Alembic commands ###
